#ifndef XPARAM_H_
#define XPARAM_H_

/* selected defines from xparameter.h file generated by design's BSP */

/* Definitions for peripheral AXI_DELAY_0 */
#define XPAR_AXI_DELAY_0_BASEADDR 0xB0000000
#define XPAR_AXI_DELAY_0_HIGHADDR 0xB0000FFF

/* Definitions for peripheral AXI_DELAY_1 */
#define XPAR_AXI_DELAY_1_BASEADDR 0xB0001000
#define XPAR_AXI_DELAY_1_HIGHADDR 0xB0001FFF

/* Definitions for peripheral AXI_TCD_0 */
#define XPAR_AXI_TCD_0_BASEADDR 0xB0100000
#define XPAR_AXI_TCD_0_HIGHADDR 0xB01FFFFF

#endif /* XPARAM_H_ */
